Use Helm for downloading charts
Switch to downloading charts with helm to ensure that hrval's
behaviour matches that of helm itself.

This addresses an issue exposed by validating a HelmRelease for
cert-manager. Jetstack ask users to configure
`https://charts.jetstack.io` as repository even though their charts
are available on `https://charts.jetstack.io/charts`.

Due to this hrval misses `/charts` when constructing `URL` which
causes `CHART_TAR` to contain the following:

```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty/1.15.8.2</center>
</body>
</html>
```

which, in turn, causes the following error when running hrval:

```
Error: file '/tmp/tmp.TTHMxU6UMe/cert-manager-v0.10.1.tgz' does not
appear to be a gzipped archive; got 'text/html; charset=utf-8'
```